#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api:
  prefix: /api
  resource: '../src/Controller/Api'

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"